name: plink
base: core20 # the base snap is the execution environment for this snap
version: '1.90p' # just for humans, typically '1.2+git' or '1.3.2'
summary:  PLINK command-line program for genomics
description:
  " Comprehensive update to Shaun Purcell's PLINK command-line program."
  The description above refers to the software: https://www.cog-genomics.org/plink/1.9/
  * I have packaged the software as a snap for **personal use** but I have made the snap available for free.
  * I do not maintain the software itself. I only maintain the snap. Please report software bugs to the maintainers.
  * Report snap-specific bugs to me.
  * I actively use this snap. It works flawlessly on my system.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0

parts:
    plink:
        # See 'snapcraft plugins'
        plugin: dump
        source:  https://s3.amazonaws.com/plink1-assets/dev/plink_linux_x86_64.zip
#        source:  ./
        prime:
            - -toy.map
            - -toy.ped

apps:
    plink:
        command: plink
        plugs:
          - home
          - network
          - removable-media
          - x11
          - wayland
          - desktop
          - desktop-legacy
          - unity7

    prettify:
        command: prettify
        plugs:
          - home
          - network
          - removable-media
          - x11
          - wayland
          - desktop
          - desktop-legacy
          - unity7

